spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fokatIndiaDB
    username: postgres
    password: root

  sql:
    init:
      mode: never


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.r2dbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
