spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fokatIndiaDB
    username: postgres
    password: root

  sql:
    init:
      mode: never



management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always



cloudinary:
  cloud-name: dgcjheuk7
  api-key: 766174979751285
  api-secret: lBRi4h7q8KG58Ntx-jdCni1SxLc


razorpay:
  key-id: rzp_test_T4CKLbZP75I7yH
  key-secret: Dy5xidrhCQU1MwyaCG2ty5FO